sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: Yaz123789
  alioss:
    endpoint: oss-cn-wuhan-lr.aliyuncs.com
    access-key-id: LTAI5tCNqemk2MLMneS9Gv3d
    access-key-secret: lDLLAbm5o1BkNZIueWP7w1lsxsHgRe
    bucket-name: mzh-take-out
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10
  wechat:
    appid: wx4d4937eae7f4372f
    secret: 6d8a5525ef85e5129a32d293b8b64a8b
    mchid: 1561414331
    mchSerialNo: 4B3B3DC35414AD50B1B755BAF8DE9CC7CF407606
    privateKeyFilePath: D:\apiclient_key.pem
    apiV3Key: CZBK51236435wxpay435434323FFDuv3
    weChatPayCertFilePath: D:\wechatpay_166D96F876F45C7D07CE98952A96EC980368ACFC.pem
    notifyUrl: https://www.weixin.qq.com/wxpay/pay.php
    refundNotifyUrl: https://www.weixin.qq.com/wxpay/pay.php
